# The hello service provides a load-balancing proxy over the hello-app
# pods. By specifying the type as a 'LoadBalancer', Kubernetes Engine will
# create an external HTTP load balancer.
apiVersion: v1
kind: Service
metadata:
  name: vite-service
spec:
  type: NodePort
  selector:
    app: vite
  ports:
  - port: 81
    targetPort: 80